package com.pfkfks.flightsuit.client;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Hulkbuster Mark 44 (DESIGN.md 4-2 헐크버스터형), built on the Hulk's silhouette (HulkModel): helmet sunk into a
 * high collar, barrel chest with the arc reactor in a gold frame, boulder pauldrons with a gold stripe,
 * gauntlets bigger than the upper arms, a thruster pack, chunky boots. Red and gold plate with seams and
 * rivets. Worn as a full set it makes its wearer half again as big (SuitSize).
 *
 * Boxes, UVs and textures/models/armor/hulkbuster_mk44.png come from tools/ModelGen.java (hulkbuster), which
 * also renders the item icons.
 */
public final class HulkbusterModel {
    private HulkbusterModel() {
    }

    // <ModelGen:hulkbuster>
    // Generated by tools/ModelGen.java - edit the layout there, not here.
    /** How much bigger than its wearer a full Hulkbuster is (SuitType.HULKBUSTER_MK44.size() must match). */
    public static final float SIZE = 1.5F;

    /** Render-time offsets of head, body, right arm, left arm, right leg, left leg (pixels). */
    public static final float[][] SHIFTS = {{0.0F, 0.0F, 0.0F}, {0.0F, 0.0F, 0.0F}, {-3.0F, 0.0F, 0.0F}, {3.0F, 0.0F, 0.0F}, {-1.1F, 0.0F, 0.0F}, {1.1F, 0.0F, 0.0F}};

    public static LayerDefinition createLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition head = root.addOrReplaceChild("head", CubeListBuilder.create(),
                PartPose.offset(0.0F, 0.0F, 0.0F));
        head.addOrReplaceChild("head_piece_head", CubeListBuilder.create()
                .texOffs(52, 0).addBox(-4.5F, -8.5F, -4.5F, 9.0F, 9.0F, 9.0F) // helmet
                .texOffs(20, 85).addBox(-3.5F, -7.0F, -5.5F, 7.0F, 5.0F, 1.0F) // faceplate
                .texOffs(46, 85).addBox(-3.5F, -1.5F, -5.5F, 7.0F, 2.0F, 2.0F) // jaw_guard
                .texOffs(0, 85).addBox(-1.5F, -9.5F, -4.0F, 3.0F, 1.0F, 7.0F), // crest
                PartPose.offset(0.0F, 0.0F, 0.0F));
        head.addOrReplaceChild("chest_piece_head", CubeListBuilder.create(),
                PartPose.offset(0.0F, 0.0F, 0.0F));
        head.addOrReplaceChild("legs_piece_head", CubeListBuilder.create(),
                PartPose.offset(0.0F, 0.0F, 0.0F));
        head.addOrReplaceChild("feet_piece_head", CubeListBuilder.create(),
                PartPose.offset(0.0F, 0.0F, 0.0F));
        root.addOrReplaceChild("hat", CubeListBuilder.create(),
                PartPose.offset(0.0F, 0.0F, 0.0F));
        PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create(),
                PartPose.offset(0.0F, 0.0F, 0.0F));
        body.addOrReplaceChild("head_piece_body", CubeListBuilder.create(),
                PartPose.offset(0.0F, 0.0F, 0.0F));
        body.addOrReplaceChild("chest_piece_body", CubeListBuilder.create()
                .texOffs(30, 62).addBox(-6.5F, -6.5F, -3.5F, 13.0F, 3.0F, 8.0F) // collar
                .texOffs(0, 0).addBox(-8.0F, -4.0F, -5.5F, 16.0F, 10.0F, 10.0F) // chest
                .texOffs(36, 85).addBox(-2.0F, 0.0F, -6.5F, 4.0F, 4.0F, 1.0F) // reactor
                .texOffs(0, 36).addBox(-6.0F, 6.0F, -4.5F, 12.0F, 5.0F, 8.0F) // abdomen
                .texOffs(0, 62).addBox(-6.0F, -3.0F, 4.5F, 12.0F, 9.0F, 3.0F) // pack
                .texOffs(88, 85).addBox(-5.0F, 6.0F, 5.0F, 3.0F, 2.0F, 2.0F) // thruster_right
                .texOffs(98, 85).addBox(2.0F, 6.0F, 5.0F, 3.0F, 2.0F, 2.0F), // thruster_left
                PartPose.offset(0.0F, 0.0F, 0.0F));
        body.addOrReplaceChild("legs_piece_body", CubeListBuilder.create()
                .texOffs(72, 62).addBox(-6.5F, 10.5F, -4.0F, 13.0F, 3.0F, 8.0F), // pelvis
                PartPose.offset(0.0F, 0.0F, 0.0F));
        body.addOrReplaceChild("feet_piece_body", CubeListBuilder.create(),
                PartPose.offset(0.0F, 0.0F, 0.0F));
        PartDefinition right_arm = root.addOrReplaceChild("right_arm", CubeListBuilder.create(),
                PartPose.offset(-5.0F, 2.0F, 0.0F));
        right_arm.addOrReplaceChild("head_piece_right_arm", CubeListBuilder.create(),
                PartPose.offset(0.0F, 0.0F, 0.0F));
        right_arm.addOrReplaceChild("chest_piece_right_arm", CubeListBuilder.create()
                .texOffs(88, 0).addBox(-6.0F, -5.0F, -5.0F, 10.0F, 6.0F, 10.0F) // pauldron_right
                .texOffs(68, 74).addBox(-4.0F, 1.0F, -3.5F, 8.0F, 4.0F, 7.0F) // upper_arm_right
                .texOffs(40, 20).addBox(-5.0F, 5.0F, -4.5F, 9.0F, 5.0F, 9.0F) // gauntlet_right
                .texOffs(40, 36).addBox(-4.5F, 10.0F, -4.0F, 8.0F, 5.0F, 8.0F), // fist_right
                PartPose.offset(0.0F, 0.0F, 0.0F));
        right_arm.addOrReplaceChild("legs_piece_right_arm", CubeListBuilder.create(),
                PartPose.offset(0.0F, 0.0F, 0.0F));
        right_arm.addOrReplaceChild("feet_piece_right_arm", CubeListBuilder.create(),
                PartPose.offset(0.0F, 0.0F, 0.0F));
        PartDefinition left_arm = root.addOrReplaceChild("left_arm", CubeListBuilder.create(),
                PartPose.offset(5.0F, 2.0F, 0.0F));
        left_arm.addOrReplaceChild("head_piece_left_arm", CubeListBuilder.create(),
                PartPose.offset(0.0F, 0.0F, 0.0F));
        left_arm.addOrReplaceChild("chest_piece_left_arm", CubeListBuilder.create()
                .texOffs(0, 20).addBox(-4.0F, -5.0F, -5.0F, 10.0F, 6.0F, 10.0F) // pauldron_left
                .texOffs(98, 74).addBox(-4.0F, 1.0F, -3.5F, 8.0F, 4.0F, 7.0F) // upper_arm_left
                .texOffs(76, 20).addBox(-4.0F, 5.0F, -4.5F, 9.0F, 5.0F, 9.0F) // gauntlet_left
                .texOffs(72, 36).addBox(-3.5F, 10.0F, -4.0F, 8.0F, 5.0F, 8.0F), // fist_left
                PartPose.offset(0.0F, 0.0F, 0.0F));
        left_arm.addOrReplaceChild("legs_piece_left_arm", CubeListBuilder.create(),
                PartPose.offset(0.0F, 0.0F, 0.0F));
        left_arm.addOrReplaceChild("feet_piece_left_arm", CubeListBuilder.create(),
                PartPose.offset(0.0F, 0.0F, 0.0F));
        PartDefinition right_leg = root.addOrReplaceChild("right_leg", CubeListBuilder.create(),
                PartPose.offset(-1.9F, 12.0F, 0.0F));
        right_leg.addOrReplaceChild("head_piece_right_leg", CubeListBuilder.create(),
                PartPose.offset(0.0F, 0.0F, 0.0F));
        right_leg.addOrReplaceChild("chest_piece_right_leg", CubeListBuilder.create(),
                PartPose.offset(0.0F, 0.0F, 0.0F));
        right_leg.addOrReplaceChild("legs_piece_right_leg", CubeListBuilder.create()
                .texOffs(0, 49).addBox(-3.5F, 0.0F, -3.5F, 7.0F, 6.0F, 7.0F) // thigh_right
                .texOffs(64, 85).addBox(-2.5F, 4.0F, -4.5F, 5.0F, 3.0F, 1.0F), // knee_right
                PartPose.offset(0.0F, 0.0F, 0.0F));
        right_leg.addOrReplaceChild("feet_piece_right_leg", CubeListBuilder.create()
                .texOffs(56, 49).addBox(-4.0F, 6.0F, -4.0F, 8.0F, 4.0F, 8.0F) // shin_right
                .texOffs(0, 74).addBox(-4.0F, 10.0F, -5.5F, 8.0F, 2.0F, 9.0F), // foot_right
                PartPose.offset(0.0F, 0.0F, 0.0F));
        PartDefinition left_leg = root.addOrReplaceChild("left_leg", CubeListBuilder.create(),
                PartPose.offset(1.9F, 12.0F, 0.0F));
        left_leg.addOrReplaceChild("head_piece_left_leg", CubeListBuilder.create(),
                PartPose.offset(0.0F, 0.0F, 0.0F));
        left_leg.addOrReplaceChild("chest_piece_left_leg", CubeListBuilder.create(),
                PartPose.offset(0.0F, 0.0F, 0.0F));
        left_leg.addOrReplaceChild("legs_piece_left_leg", CubeListBuilder.create()
                .texOffs(28, 49).addBox(-3.5F, 0.0F, -3.5F, 7.0F, 6.0F, 7.0F) // thigh_left
                .texOffs(76, 85).addBox(-2.5F, 4.0F, -4.5F, 5.0F, 3.0F, 1.0F), // knee_left
                PartPose.offset(0.0F, 0.0F, 0.0F));
        left_leg.addOrReplaceChild("feet_piece_left_leg", CubeListBuilder.create()
                .texOffs(88, 49).addBox(-4.0F, 6.0F, -4.0F, 8.0F, 4.0F, 8.0F) // shin_left
                .texOffs(34, 74).addBox(-4.0F, 10.0F, -5.5F, 8.0F, 2.0F, 9.0F), // foot_left
                PartPose.offset(0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 128, 128);
    }
    // </ModelGen:hulkbuster>
}
