package com.pfkfks.flightsuit.client;

import com.pfkfks.flightsuit.FlightSuitMod;
import com.pfkfks.flightsuit.hero.CityHeroEntity;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.util.Mth;

/**
 * The Hulk (DESIGN.md 4-13): a body of his own instead of a scaled-up player - a small head hung low and
 * forward between huge traps, a barrel chest, boulder shoulders, forearms thicker than the upper arms and fists
 * that hang past the hips, short thick legs in torn purple shorts. His arms hang out wide, and every swing is
 * both fists brought down from overhead.
 *
 * Boxes, UVs and textures/entity/hero/hulk_model.png come from tools/ModelGen.java (hulk).
 */
public class HulkModel extends ShiftedHumanoidModel<CityHeroEntity> {
    public static final ModelLayerLocation LAYER = new ModelLayerLocation(new ResourceLocation(FlightSuitMod.MODID, "hulk"), "main");

    public HulkModel(ModelPart root) {
        super(root, SHIFTS);
    }

    @Override
    public void setupAnim(CityHeroEntity hulk, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
        super.setupAnim(hulk, limbSwing, limbSwingAmount, ageInTicks, netHeadYaw, headPitch);
        // Arms out from the body (they're too big to hang straight) and a heavy, rolling walk.
        float breathe = Mth.sin(ageInTicks * 0.08F) * 0.04F;
        rightArm.zRot += 0.22F + breathe;
        leftArm.zRot -= 0.22F + breathe;
        // Every swing is a smash: both fists up overhead, then brought down together.
        if (attackTime > 0.0F) {
            float raise = attackTime < 0.5F ? attackTime / 0.5F : 1.0F - (attackTime - 0.5F) / 0.5F * 1.3F;
            rightArm.xRot = -2.8F * raise;
            leftArm.xRot = -2.8F * raise;
            rightArm.zRot = 0.15F;
            leftArm.zRot = -0.15F;
        }
    }

    // <ModelGen:hulk>
    // Generated by tools/ModelGen.java - edit the layout there, not here.
    /** How much bigger than a player the Hulk is drawn (his hitbox is HeroType.HULK's scale). */
    public static final float SCALE = 1.5F;

    /** Render-time offsets of head, body, right arm, left arm, right leg, left leg (pixels). */
    public static final float[][] SHIFTS = {{0.0F, 0.5F, -2.0F}, {0.0F, 0.0F, 0.0F}, {-3.0F, 0.0F, 0.0F}, {3.0F, 0.0F, 0.0F}, {-1.4F, 0.0F, 0.0F}, {1.4F, 0.0F, 0.0F}};

    public static LayerDefinition createLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("head", CubeListBuilder.create()
                .texOffs(50, 0).addBox(-4.0F, -8.0F, -4.0F, 8.0F, 8.0F, 8.0F) // skull
                .texOffs(82, 69).addBox(-4.5F, -6.0F, -5.0F, 9.0F, 2.0F, 1.0F) // brow
                .texOffs(52, 69).addBox(-3.5F, -2.5F, -5.0F, 7.0F, 3.0F, 2.0F) // jaw
                .texOffs(42, 47).addBox(-4.5F, -8.5F, -3.5F, 9.0F, 3.0F, 8.0F) // hair
                .texOffs(70, 69).addBox(-4.5F, -4.5F, -1.0F, 1.0F, 2.0F, 2.0F) // ear_right
                .texOffs(76, 69).addBox(3.5F, -4.5F, -1.0F, 1.0F, 2.0F, 2.0F), // ear_left
                PartPose.offset(0.0F, 0.0F, 0.0F));
        root.addOrReplaceChild("hat", CubeListBuilder.create(),
                PartPose.offset(0.0F, 0.0F, 0.0F));
        root.addOrReplaceChild("body", CubeListBuilder.create()
                .texOffs(28, 58).addBox(-6.0F, -6.0F, -3.0F, 12.0F, 2.0F, 7.0F) // traps
                .texOffs(0, 0).addBox(-8.0F, -4.0F, -5.0F, 16.0F, 10.0F, 9.0F) // chest
                .texOffs(76, 34).addBox(-6.0F, 6.0F, -4.0F, 12.0F, 5.0F, 7.0F) // abs
                .texOffs(0, 47).addBox(-6.5F, 10.0F, -4.5F, 13.0F, 3.0F, 8.0F), // waist
                PartPose.offset(0.0F, 0.0F, 0.0F));
        root.addOrReplaceChild("right_arm", CubeListBuilder.create()
                .texOffs(82, 0).addBox(-5.0F, -6.0F, -4.0F, 8.0F, 7.0F, 8.0F) // shoulder_right
                .texOffs(96, 19).addBox(-4.5F, 1.0F, -3.5F, 7.0F, 6.0F, 7.0F) // upper_arm_right
                .texOffs(32, 19).addBox(-5.0F, 7.0F, -4.0F, 8.0F, 6.0F, 8.0F) // forearm_right
                .texOffs(76, 47).addBox(-4.5F, 13.0F, -3.5F, 7.0F, 4.0F, 7.0F), // fist_right
                PartPose.offset(-5.0F, 2.0F, 0.0F));
        root.addOrReplaceChild("left_arm", CubeListBuilder.create()
                .texOffs(0, 19).addBox(-3.0F, -6.0F, -4.0F, 8.0F, 7.0F, 8.0F) // shoulder_left
                .texOffs(0, 34).addBox(-2.5F, 1.0F, -3.5F, 7.0F, 6.0F, 7.0F) // upper_arm_left
                .texOffs(64, 19).addBox(-3.0F, 7.0F, -4.0F, 8.0F, 6.0F, 8.0F) // forearm_left
                .texOffs(0, 58).addBox(-2.5F, 13.0F, -3.5F, 7.0F, 4.0F, 7.0F), // fist_left
                PartPose.offset(5.0F, 2.0F, 0.0F));
        root.addOrReplaceChild("right_leg", CubeListBuilder.create()
                .texOffs(28, 34).addBox(-3.0F, 0.0F, -3.0F, 6.0F, 7.0F, 6.0F) // thigh_right
                .texOffs(66, 58).addBox(-2.5F, 7.0F, -2.5F, 5.0F, 4.0F, 5.0F) // shin_right
                .texOffs(0, 69).addBox(-3.0F, 11.0F, -4.0F, 6.0F, 1.0F, 7.0F), // foot_right
                PartPose.offset(-1.9F, 12.0F, 0.0F));
        root.addOrReplaceChild("left_leg", CubeListBuilder.create()
                .texOffs(52, 34).addBox(-3.0F, 0.0F, -3.0F, 6.0F, 7.0F, 6.0F) // thigh_left
                .texOffs(86, 58).addBox(-2.5F, 7.0F, -2.5F, 5.0F, 4.0F, 5.0F) // shin_left
                .texOffs(26, 69).addBox(-3.0F, 11.0F, -4.0F, 6.0F, 1.0F, 7.0F), // foot_left
                PartPose.offset(1.9F, 12.0F, 0.0F));
        return LayerDefinition.create(mesh, 128, 128);
    }
    // </ModelGen:hulk>
}
