package com.pfkfks.flightsuit.client;

import com.pfkfks.flightsuit.FlightSuitMod;
import com.pfkfks.flightsuit.planet.dbz.DbzAction;
import com.pfkfks.flightsuit.planet.dbz.DbzFighterEntity;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.util.Mth;

/**
 * Vegeta's Great Ape (M17): a body of its own, four times a player's size - long arms that swing low, a tail that
 * sways behind, both fists hammering down when it attacks or stamps, the arms thrown up when it roars (TRANSFORM).
 *
 * Boxes, UVs and textures/entity/dbz/oozaru_vegeta.png come from tools/ModelGen.java (oozaru).
 */
public class OozaruModel extends ShiftedHumanoidModel<DbzFighterEntity> {
    public static final ModelLayerLocation LAYER = new ModelLayerLocation(new ResourceLocation(FlightSuitMod.MODID, "oozaru"), "main");

    private final ModelPart tail;

    public OozaruModel(ModelPart root) {
        super(root, SHIFTS);
        this.tail = body.getChild("tail");
    }

    @Override
    public void setupAnim(DbzFighterEntity ape, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
        super.setupAnim(ape, limbSwing, limbSwingAmount, ageInTicks, netHeadYaw, headPitch);
        rightArm.zRot += 0.18F;
        leftArm.zRot -= 0.18F;
        tail.yRot = Mth.sin(ageInTicks * 0.12F) * 0.5F;
        tail.xRot = 0.5F + Mth.sin(ageInTicks * 0.09F) * 0.15F;
        DbzAction action = ape.getAction();
        float age = ape.actionAge(ageInTicks - ape.tickCount);
        switch (action) {
            case PUNCH_L, PUNCH_R, KICK -> {
                float t = Mth.clamp(age / Math.max(1, action.ticks()), 0.0F, 1.0F);
                float raise = t < 0.4F ? t / 0.4F : 1.0F - (t - 0.4F) / 0.6F * 1.3F;
                rightArm.xRot = -2.6F * raise;
                leftArm.xRot = -2.6F * raise;
            }
            case TRANSFORM -> {
                rightArm.xRot = -2.9F;
                leftArm.xRot = -2.9F;
                rightArm.zRot = -0.4F;
                leftArm.zRot = 0.4F;
                head.xRot = -0.6F;
            }
            case FIRE -> head.xRot = -0.2F;
            case HURT -> {
                body.xRot = -0.25F;
                head.xRot = -0.5F;
                rightArm.zRot = 0.7F;
                leftArm.zRot = -0.7F;
            }
            case DOWN -> {
                rightArm.zRot = 0.5F;
                leftArm.zRot = -0.5F;
            }
            default -> {
            }
        }
        hat.copyFrom(head);
    }

    // <ModelGen:oozaru>
    // Generated by tools/ModelGen.java - edit the layout there, not here.
    /** How much bigger than a player the Great Ape is drawn (its hitbox is DbzCharacter.OOZARU_VEGETA's scale). */
    public static final float SCALE = 4.0F;

    /** Render-time offsets of head, body, right arm, left arm, right leg, left leg (pixels). */
    public static final float[][] SHIFTS = {{0.0F, 1.0F, -1.5F}, {0.0F, 0.0F, 0.0F}, {-2.5F, 0.0F, 0.0F}, {2.5F, 0.0F, 0.0F}, {-1.3F, 0.0F, 0.0F}, {1.3F, 0.0F, 0.0F}};

    public static LayerDefinition createLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("head", CubeListBuilder.create()
                .texOffs(44, 0).addBox(-4.5F, -8.0F, -4.5F, 9.0F, 8.0F, 9.0F) // skull
                .texOffs(56, 64).addBox(-4.5F, -7.0F, -5.5F, 9.0F, 2.0F, 1.0F) // brow
                .texOffs(26, 64).addBox(-3.0F, -3.5F, -7.5F, 6.0F, 4.0F, 3.0F) // muzzle
                .texOffs(0, 30).addBox(-5.0F, -9.5F, -3.0F, 10.0F, 4.0F, 8.0F) // mane
                .texOffs(44, 64).addBox(-5.5F, -6.0F, -1.0F, 1.0F, 3.0F, 2.0F) // ear_right
                .texOffs(50, 64).addBox(4.5F, -6.0F, -1.0F, 1.0F, 3.0F, 2.0F), // ear_left
                PartPose.offset(0.0F, 0.0F, 0.0F));
        root.addOrReplaceChild("hat", CubeListBuilder.create(),
                PartPose.offset(0.0F, 0.0F, 0.0F));
        PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create()
                .texOffs(0, 0).addBox(-7.0F, -2.0F, -4.0F, 14.0F, 9.0F, 8.0F) // chest
                .texOffs(76, 17).addBox(-6.0F, 7.0F, -3.5F, 12.0F, 5.0F, 7.0F), // belly
                PartPose.offset(0.0F, 0.0F, 0.0F));
        body.addOrReplaceChild("tail", CubeListBuilder.create()
                .texOffs(0, 64).addBox(-1.5F, -1.5F, 0.0F, 3.0F, 3.0F, 6.0F) // tail_base
                .texOffs(18, 64).addBox(-1.0F, -6.5F, 5.0F, 2.0F, 6.0F, 2.0F), // tail_tip
                PartPose.offsetAndRotation(0.0F, 10.0F, 3.5F, 0.5F, 0.0F, 0.0F));
        root.addOrReplaceChild("right_arm", CubeListBuilder.create()
                .texOffs(80, 0).addBox(-4.5F, -3.0F, -3.5F, 7.0F, 6.0F, 7.0F) // shoulder_right
                .texOffs(24, 42).addBox(-5.0F, -4.0F, -4.0F, 8.0F, 3.0F, 8.0F) // pad_right
                .texOffs(36, 30).addBox(-4.0F, 3.0F, -3.0F, 6.0F, 6.0F, 6.0F) // upper_arm_right
                .texOffs(60, 30).addBox(-4.0F, 9.0F, -3.0F, 6.0F, 6.0F, 6.0F) // forearm_right
                .texOffs(88, 42).addBox(-4.0F, 15.0F, -3.0F, 6.0F, 4.0F, 6.0F), // hand_right
                PartPose.offset(-5.0F, 2.0F, 0.0F));
        root.addOrReplaceChild("left_arm", CubeListBuilder.create()
                .texOffs(0, 17).addBox(-2.5F, -3.0F, -3.5F, 7.0F, 6.0F, 7.0F) // shoulder_left
                .texOffs(56, 42).addBox(-3.0F, -4.0F, -4.0F, 8.0F, 3.0F, 8.0F) // pad_left
                .texOffs(84, 30).addBox(-2.0F, 3.0F, -3.0F, 6.0F, 6.0F, 6.0F) // upper_arm_left
                .texOffs(0, 42).addBox(-2.0F, 9.0F, -3.0F, 6.0F, 6.0F, 6.0F) // forearm_left
                .texOffs(0, 54).addBox(-2.0F, 15.0F, -3.0F, 6.0F, 4.0F, 6.0F), // hand_left
                PartPose.offset(5.0F, 2.0F, 0.0F));
        root.addOrReplaceChild("right_leg", CubeListBuilder.create()
                .texOffs(28, 17).addBox(-3.0F, 0.0F, -3.0F, 6.0F, 7.0F, 6.0F) // thigh_right
                .texOffs(80, 54).addBox(-2.5F, 7.0F, -2.5F, 5.0F, 4.0F, 5.0F) // shin_right
                .texOffs(24, 54).addBox(-3.0F, 11.0F, -4.5F, 6.0F, 1.0F, 8.0F), // foot_right
                PartPose.offset(-1.9F, 12.0F, 0.0F));
        root.addOrReplaceChild("left_leg", CubeListBuilder.create()
                .texOffs(52, 17).addBox(-3.0F, 0.0F, -3.0F, 6.0F, 7.0F, 6.0F) // thigh_left
                .texOffs(100, 54).addBox(-2.5F, 7.0F, -2.5F, 5.0F, 4.0F, 5.0F) // shin_left
                .texOffs(52, 54).addBox(-3.0F, 11.0F, -4.5F, 6.0F, 1.0F, 8.0F), // foot_left
                PartPose.offset(1.9F, 12.0F, 0.0F));
        return LayerDefinition.create(mesh, 128, 128);
    }
    // </ModelGen:oozaru>
}
