package com.pfkfks.flightsuit.client;

import com.pfkfks.flightsuit.FlightSuitMod;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.resources.ResourceLocation;

/**
 * Shenron's pieces, placed one by one along his spine by ShenronRenderer: a body segment (scaled to each
 * stretch of the body - dark scales on the back, cream belly plates, a dorsal fin), the head (snout, glowing red
 * eyes, brow ridges, crest, cheek frills, antlers, an opening jaw), an arm (shoulder, forearm, three claws)
 * and one whisker link. Every piece faces -Z (toward the head) with its back up (-Y).
 *
 * Boxes, UVs and textures/entity/dbz/shenron.png come from tools/ModelGen.java (shenron).
 */
public class ShenronModel {
    public static final ModelLayerLocation LAYER = new ModelLayerLocation(new ResourceLocation(FlightSuitMod.MODID, "shenron"), "main");

    final ModelPart segment;
    final ModelPart head;
    final ModelPart jaw;
    final ModelPart arm;
    final ModelPart forearm;
    final ModelPart hand;
    final ModelPart whisker;

    public ShenronModel(ModelPart root) {
        segment = root.getChild("segment");
        head = root.getChild("head");
        jaw = head.getChild("jaw");
        arm = root.getChild("arm");
        forearm = arm.getChild("forearm");
        hand = forearm.getChild("hand");
        whisker = root.getChild("whisker");
    }

    // <ModelGen:shenron>
    // Generated by tools/ModelGen.java - edit the layout there, not here.
    public static LayerDefinition createLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("segment", CubeListBuilder.create()
                .texOffs(0, 0).addBox(-6.0F, -6.0F, -8.0F, 12.0F, 12.0F, 16.0F) // core
                .texOffs(0, 28).addBox(-4.5F, 5.5F, -8.0F, 9.0F, 1.0F, 16.0F) // belly
                .texOffs(80, 28).addBox(-0.5F, -9.0F, -6.0F, 1.0F, 3.0F, 9.0F), // fin
                PartPose.offset(0.0F, 0.0F, 0.0F));
        PartDefinition head = root.addOrReplaceChild("head", CubeListBuilder.create()
                .texOffs(56, 0).addBox(-5.0F, -6.0F, -6.0F, 10.0F, 8.0F, 10.0F) // skull
                .texOffs(50, 28).addBox(-3.5F, -4.0F, -14.0F, 7.0F, 5.0F, 8.0F) // snout
                .texOffs(70, 56).addBox(-2.5F, -5.0F, -14.0F, 5.0F, 1.0F, 3.0F) // nose
                .texOffs(102, 45).addBox(-3.0F, 1.0F, -13.5F, 6.0F, 1.0F, 7.0F) // upper_teeth
                .texOffs(30, 56).addBox(-5.5F, -7.0F, -7.0F, 4.0F, 2.0F, 4.0F) // brow_right
                .texOffs(46, 56).addBox(1.5F, -7.0F, -7.0F, 4.0F, 2.0F, 4.0F) // brow_left
                .texOffs(86, 45).addBox(-0.5F, -8.0F, -3.0F, 1.0F, 2.0F, 7.0F) // crest
                .texOffs(32, 45).addBox(-6.5F, -5.0F, 0.0F, 1.0F, 6.0F, 5.0F) // frill_right
                .texOffs(44, 45).addBox(5.5F, -5.0F, 0.0F, 1.0F, 6.0F, 5.0F), // frill_left
                PartPose.offset(0.0F, 0.0F, 0.0F));
        head.addOrReplaceChild("jaw", CubeListBuilder.create()
                .texOffs(0, 45).addBox(-3.5F, 0.0F, -8.5F, 7.0F, 2.0F, 9.0F) // jaw
                .texOffs(8, 56).addBox(-2.5F, -1.0F, -7.5F, 5.0F, 1.0F, 6.0F), // lower_teeth
                PartPose.offset(0.0F, 2.0F, -5.0F));
        PartDefinition horn_right = head.addOrReplaceChild("horn_right", CubeListBuilder.create()
                .texOffs(100, 28).addBox(-1.0F, -10.0F, -1.0F, 2.0F, 10.0F, 2.0F), // horn_right
                PartPose.offsetAndRotation(-3.5F, -6.0F, 1.0F, -0.9F, 0.0F, -0.35F));
        horn_right.addOrReplaceChild("tine_right", CubeListBuilder.create()
                .texOffs(62, 56).addBox(-0.5F, -4.0F, -0.5F, 1.0F, 4.0F, 1.0F), // tine_right
                PartPose.offsetAndRotation(0.0F, -6.0F, 0.0F, 0.9F, 0.0F, 0.0F));
        PartDefinition horn_left = head.addOrReplaceChild("horn_left", CubeListBuilder.create()
                .texOffs(108, 28).addBox(-1.0F, -10.0F, -1.0F, 2.0F, 10.0F, 2.0F), // horn_left
                PartPose.offsetAndRotation(3.5F, -6.0F, 1.0F, -0.9F, 0.0F, 0.35F));
        horn_left.addOrReplaceChild("tine_left", CubeListBuilder.create()
                .texOffs(66, 56).addBox(-0.5F, -4.0F, -0.5F, 1.0F, 4.0F, 1.0F), // tine_left
                PartPose.offsetAndRotation(0.0F, -6.0F, 0.0F, 0.9F, 0.0F, 0.0F));
        PartDefinition arm = root.addOrReplaceChild("arm", CubeListBuilder.create()
                .texOffs(56, 45).addBox(-1.5F, 0.0F, -1.5F, 3.0F, 7.0F, 3.0F), // upper
                PartPose.offset(0.0F, 0.0F, 0.0F));
        PartDefinition forearm = arm.addOrReplaceChild("forearm", CubeListBuilder.create()
                .texOffs(0, 56).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 6.0F, 2.0F), // forearm
                PartPose.offsetAndRotation(0.0F, 7.0F, 0.0F, -0.9F, 0.0F, 0.0F));
        forearm.addOrReplaceChild("hand", CubeListBuilder.create()
                .texOffs(86, 56).addBox(-1.5F, 0.0F, -1.5F, 3.0F, 1.0F, 3.0F) // palm
                .texOffs(98, 56).addBox(-1.5F, 1.0F, -1.5F, 1.0F, 3.0F, 1.0F) // claw_a
                .texOffs(102, 56).addBox(0.5F, 1.0F, -1.5F, 1.0F, 3.0F, 1.0F) // claw_b
                .texOffs(106, 56).addBox(-0.5F, 1.0F, 0.5F, 1.0F, 3.0F, 1.0F), // claw_c
                PartPose.offsetAndRotation(0.0F, 6.0F, 0.0F, 0.5F, 0.0F, 0.0F));
        root.addOrReplaceChild("whisker", CubeListBuilder.create()
                .texOffs(68, 45).addBox(-0.5F, -0.5F, -8.0F, 1.0F, 1.0F, 8.0F), // whisker
                PartPose.offset(0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 128, 128);
    }
    // </ModelGen:shenron>
}
