package com.pfkfks.flightsuit.client;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Trunks Mark 5: the user's Trunks skin (docs/reference/trunks_mk5_skin_source.png, left half of the texture)
 * as the suit's base, with the parts a skin can't do in 3D on top - lavender hair with volume (crown, side
 * curtains, back, forehead locks), the jacket's stand-up collar and rolled cuffs, the sword on his back (hilt
 * over the right shoulder, sheath to the left hip) and the big yellow boot cuffs. Legs split at the knee:
 * thighs are the leggings, shins the boots.
 *
 * Boxes, UVs and textures/models/armor/trunks_mk5.png come from tools/ModelGen.java (trunks).
 */
public final class TrunksSuitModel {
    private TrunksSuitModel() {
    }

    // <ModelGen:trunks_mk5>
    // Generated by tools/ModelGen.java - edit the layout there, not here.
    /** Render-time offsets of head, body, right arm, left arm, right leg, left leg (pixels). */
    public static final float[][] SHIFTS = {{0.0F, 0.0F, 0.0F}, {0.0F, 0.0F, 0.0F}, {0.0F, 0.0F, 0.0F}, {0.0F, 0.0F, 0.0F}, {0.0F, 0.0F, 0.0F}, {0.0F, 0.0F, 0.0F}};

    public static LayerDefinition createLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition head = root.addOrReplaceChild("head", CubeListBuilder.create(),
                PartPose.offset(0.0F, 0.0F, 0.0F));
        head.addOrReplaceChild("head_piece_head", CubeListBuilder.create()
                .texOffs(0, 0).addBox(-4.0F, -8.0F, -4.0F, 8.0F, 8.0F, 8.0F, new CubeDeformation(0.75F)) // head
                .texOffs(32, 0).addBox(-4.0F, -8.0F, -4.0F, 8.0F, 8.0F, 8.0F, new CubeDeformation(1.0F)) // hat
                .texOffs(64, 15).addBox(-4.5F, -10.0F, -4.5F, 9.0F, 1.0F, 9.0F) // crown
                .texOffs(64, 0).addBox(-5.5F, -9.0F, -4.0F, 1.0F, 7.0F, 8.0F) // hair_right
                .texOffs(82, 0).addBox(4.5F, -9.0F, -4.0F, 1.0F, 7.0F, 8.0F) // hair_left
                .texOffs(100, 15).addBox(-5.0F, -9.0F, 4.5F, 10.0F, 8.0F, 1.0F) // hair_back
                .texOffs(118, 41).addBox(-4.0F, -9.0F, -5.5F, 3.0F, 3.0F, 1.0F) // lock_right
                .texOffs(64, 47).addBox(1.0F, -9.0F, -5.5F, 3.0F, 3.0F, 1.0F), // lock_left
                PartPose.offset(0.0F, 0.0F, 0.0F));
        head.addOrReplaceChild("chest_piece_head", CubeListBuilder.create(),
                PartPose.offset(0.0F, 0.0F, 0.0F));
        head.addOrReplaceChild("legs_piece_head", CubeListBuilder.create(),
                PartPose.offset(0.0F, 0.0F, 0.0F));
        head.addOrReplaceChild("feet_piece_head", CubeListBuilder.create(),
                PartPose.offset(0.0F, 0.0F, 0.0F));
        root.addOrReplaceChild("hat", CubeListBuilder.create(),
                PartPose.offset(0.0F, 0.0F, 0.0F));
        PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create(),
                PartPose.offset(0.0F, 0.0F, 0.0F));
        body.addOrReplaceChild("head_piece_body", CubeListBuilder.create(),
                PartPose.offset(0.0F, 0.0F, 0.0F));
        PartDefinition chest_piece_body = body.addOrReplaceChild("chest_piece_body", CubeListBuilder.create()
                .texOffs(16, 16).addBox(-4.0F, 0.0F, -2.0F, 8.0F, 12.0F, 4.0F, new CubeDeformation(0.4F)) // body
                .texOffs(16, 32).addBox(-4.0F, 0.0F, -2.0F, 8.0F, 12.0F, 4.0F, new CubeDeformation(0.65F)) // jacket
                .texOffs(72, 47).addBox(-5.0F, -2.0F, 2.0F, 10.0F, 2.0F, 1.0F) // collar_back
                .texOffs(112, 33).addBox(-5.0F, -2.0F, -2.0F, 1.0F, 2.0F, 4.0F) // collar_right
                .texOffs(64, 41).addBox(4.0F, -2.0F, -2.0F, 1.0F, 2.0F, 4.0F), // collar_left
                PartPose.offset(0.0F, 0.0F, 0.0F));
        chest_piece_body.addOrReplaceChild("sheath", CubeListBuilder.create()
                .texOffs(100, 0).addBox(-1.0F, -5.0F, -0.5F, 2.0F, 14.0F, 1.0F) // scabbard
                .texOffs(94, 47).addBox(-1.5F, 9.0F, -1.0F, 3.0F, 1.0F, 2.0F) // chape
                .texOffs(104, 47).addBox(-1.5F, -6.0F, -1.0F, 3.0F, 1.0F, 2.0F) // throat
                .texOffs(78, 41).addBox(-2.5F, -7.0F, -1.5F, 5.0F, 1.0F, 3.0F) // guard
                .texOffs(74, 41).addBox(-0.5F, -12.0F, -0.5F, 1.0F, 5.0F, 1.0F) // grip
                .texOffs(114, 47).addBox(-1.0F, -13.0F, -1.0F, 2.0F, 1.0F, 2.0F), // pommel
                PartPose.offsetAndRotation(0.0F, 4.5F, 3.4F, 0.0F, 0.0F, -0.55F));
        body.addOrReplaceChild("legs_piece_body", CubeListBuilder.create(),
                PartPose.offset(0.0F, 0.0F, 0.0F));
        body.addOrReplaceChild("feet_piece_body", CubeListBuilder.create(),
                PartPose.offset(0.0F, 0.0F, 0.0F));
        PartDefinition right_arm = root.addOrReplaceChild("right_arm", CubeListBuilder.create(),
                PartPose.offset(-5.0F, 2.0F, 0.0F));
        right_arm.addOrReplaceChild("head_piece_right_arm", CubeListBuilder.create(),
                PartPose.offset(0.0F, 0.0F, 0.0F));
        right_arm.addOrReplaceChild("chest_piece_right_arm", CubeListBuilder.create()
                .texOffs(40, 16).addBox(-3.0F, -2.0F, -2.0F, 4.0F, 12.0F, 4.0F, new CubeDeformation(0.4F)) // arm
                .texOffs(40, 32).addBox(-3.0F, -2.0F, -2.0F, 4.0F, 12.0F, 4.0F, new CubeDeformation(0.65F)) // sleeve
                .texOffs(64, 25).addBox(-4.0F, 5.0F, -3.0F, 6.0F, 2.0F, 6.0F), // cuff_right
                PartPose.offset(0.0F, 0.0F, 0.0F));
        right_arm.addOrReplaceChild("legs_piece_right_arm", CubeListBuilder.create(),
                PartPose.offset(0.0F, 0.0F, 0.0F));
        right_arm.addOrReplaceChild("feet_piece_right_arm", CubeListBuilder.create(),
                PartPose.offset(0.0F, 0.0F, 0.0F));
        PartDefinition left_arm = root.addOrReplaceChild("left_arm", CubeListBuilder.create(),
                PartPose.offset(5.0F, 2.0F, 0.0F));
        left_arm.addOrReplaceChild("head_piece_left_arm", CubeListBuilder.create(),
                PartPose.offset(0.0F, 0.0F, 0.0F));
        left_arm.addOrReplaceChild("chest_piece_left_arm", CubeListBuilder.create()
                .texOffs(32, 48).addBox(-1.0F, -2.0F, -2.0F, 4.0F, 12.0F, 4.0F, new CubeDeformation(0.4F)) // arm
                .texOffs(48, 48).addBox(-1.0F, -2.0F, -2.0F, 4.0F, 12.0F, 4.0F, new CubeDeformation(0.65F)) // sleeve
                .texOffs(88, 25).addBox(-2.0F, 5.0F, -3.0F, 6.0F, 2.0F, 6.0F), // cuff_left
                PartPose.offset(0.0F, 0.0F, 0.0F));
        left_arm.addOrReplaceChild("legs_piece_left_arm", CubeListBuilder.create(),
                PartPose.offset(0.0F, 0.0F, 0.0F));
        left_arm.addOrReplaceChild("feet_piece_left_arm", CubeListBuilder.create(),
                PartPose.offset(0.0F, 0.0F, 0.0F));
        PartDefinition right_leg = root.addOrReplaceChild("right_leg", CubeListBuilder.create(),
                PartPose.offset(-1.9F, 12.0F, 0.0F));
        right_leg.addOrReplaceChild("head_piece_right_leg", CubeListBuilder.create(),
                PartPose.offset(0.0F, 0.0F, 0.0F));
        right_leg.addOrReplaceChild("chest_piece_right_leg", CubeListBuilder.create(),
                PartPose.offset(0.0F, 0.0F, 0.0F));
        right_leg.addOrReplaceChild("legs_piece_right_leg", CubeListBuilder.create()
                .texOffs(0, 16).addBox(-2.0F, 0.0F, -2.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.3F)) // thigh
                .texOffs(0, 32).addBox(-2.0F, 0.0F, -2.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.55F)), // thigh_pants
                PartPose.offset(0.0F, 0.0F, 0.0F));
        right_leg.addOrReplaceChild("feet_piece_right_leg", CubeListBuilder.create()
                .texOffs(0, 24).addBox(-2.0F, 8.0F, -2.0F, 4.0F, 4.0F, 4.0F, new CubeDeformation(0.5F)) // shin
                .texOffs(0, 40).addBox(-2.0F, 8.0F, -2.0F, 4.0F, 4.0F, 4.0F, new CubeDeformation(0.75F)) // shin_pants
                .texOffs(64, 33).addBox(-3.0F, 7.0F, -3.0F, 6.0F, 2.0F, 6.0F) // boot_cuff_right
                .texOffs(94, 41).addBox(-2.0F, 10.0F, -4.0F, 4.0F, 2.0F, 2.0F), // toe_right
                PartPose.offset(0.0F, 0.0F, 0.0F));
        PartDefinition left_leg = root.addOrReplaceChild("left_leg", CubeListBuilder.create(),
                PartPose.offset(1.9F, 12.0F, 0.0F));
        left_leg.addOrReplaceChild("head_piece_left_leg", CubeListBuilder.create(),
                PartPose.offset(0.0F, 0.0F, 0.0F));
        left_leg.addOrReplaceChild("chest_piece_left_leg", CubeListBuilder.create(),
                PartPose.offset(0.0F, 0.0F, 0.0F));
        left_leg.addOrReplaceChild("legs_piece_left_leg", CubeListBuilder.create()
                .texOffs(16, 48).addBox(-2.0F, 0.0F, -2.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.3F)) // thigh
                .texOffs(0, 48).addBox(-2.0F, 0.0F, -2.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.55F)), // thigh_pants
                PartPose.offset(0.0F, 0.0F, 0.0F));
        left_leg.addOrReplaceChild("feet_piece_left_leg", CubeListBuilder.create()
                .texOffs(16, 56).addBox(-2.0F, 8.0F, -2.0F, 4.0F, 4.0F, 4.0F, new CubeDeformation(0.5F)) // shin
                .texOffs(0, 56).addBox(-2.0F, 8.0F, -2.0F, 4.0F, 4.0F, 4.0F, new CubeDeformation(0.75F)) // shin_pants
                .texOffs(88, 33).addBox(-3.0F, 7.0F, -3.0F, 6.0F, 2.0F, 6.0F) // boot_cuff_left
                .texOffs(106, 41).addBox(-2.0F, 10.0F, -4.0F, 4.0F, 2.0F, 2.0F), // toe_left
                PartPose.offset(0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 128, 64);
    }
    // </ModelGen:trunks_mk5>
}
